### ISSUE TITLE
Add version

### ISSUE THREAD

**Issue by martinberoiz** [moemyself3/lightcurve#2]
Add `__version__` property to module.

**Comment by moemyself3** [comment]
I thought I already did. Please let me know if I need anything else aside from this.

https://github.com/moemyself3/lightcurve/blob/aa82ba685a02ab237b7c81c4b5a3cae5d13fd3c6/lightcurve.py#L13

**Comment by martinberoiz** [comment]
oh, you're right, I'm sorry.
